rootProject.name = 'wise-task-library'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://maven.pkg.github.com/wisetask/wise-task-library'
            credentials {
                username = System.getenv("USERNAME") ?: "wisetask"
                password = System.getenv("TOKEN")
            }
        }
    }
}